// 9. BREAKOUT ROOM
const BREAKOUT_ROOM_JOIN_DETAILS = 'BREAKOUT_ROOM_BREAKOUT_ROOM_JOIN_DETAILS';
const BREAKOUT_ROOM_SYNC_STATE = 'BREAKOUT_ROOM_BREAKOUT_ROOM_STATE';
const BREAKOUT_ROOM_ANNOUNCEMENT = 'BREAKOUT_ROOM_ANNOUNCEMENT';
const BREAKOUT_ROOM_MAKE_PRESENTER = 'BREAKOUT_ROOM_MAKE_PRESENTER';
const BREAKOUT_ROOM_HOST_OPERATION_START = 'BREAKOUT_ROOM_HOST_OPERATION_START';
const BREAKOUT_ROOM_HOST_OPERATION_END = 'BREAKOUT_ROOM_HOST_OPERATION_END';

const BreakoutRoomEventNames = {
  BREAKOUT_ROOM_JOIN_DETAILS,
  BREAKOUT_ROOM_SYNC_STATE,
  BREAKOUT_ROOM_ANNOUNCEMENT,
  BREAKOUT_ROOM_MAKE_PRESENTER,
  BREAKOUT_ROOM_HOST_OPERATION_START,
  BREAKOUT_ROOM_HOST_OPERATION_END,
};
export {BreakoutRoomEventNames};
