// 9. BREAKOUT ROOM
const BREAKOUT_ROOM_JOIN_DETAILS = 'BREAKOUT_ROOM_BREAKOUT_ROOM_JOIN_DETAILS';
const BREAKOUT_ROOM_ANNOUNCEMENT = 'BREAKOUT_ROOM_ANNOUNCEMENT';
const BREAKOUT_ROOM_MAKE_PRESENTER = 'BREAKOUT_ROOM_MAKE_PRESENTER';

const BreakoutRoomEventNames = {
  BREAKOUT_ROOM_JOIN_DETAILS,
  BREAKOUT_ROOM_ANNOUNCEMENT,
  BREAKOUT_ROOM_MAKE_PRESENTER,
};
export {BreakoutRoomEventNames};
