import {Platform, Dimensions} from 'react-native';

const {width} = Dimensions.get('window');

const styles = {
  main: {
    flex: 1,
    backgroundColor: '#333237',
    flexDirection: 'column',
    paddingHorizontal: Platform.OS === 'web' ? '1%' : 0,
  },
  full: {
    flex: 1,
  },
  navbar: {
    flex: 1,
    backgroundColor: '#333237',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  participantNav: {
    backgroundColor: '#565658',
    flex: 0.2,
    maxWidth: 65,
    paddingHorizontal: 5,
    marginHorizontal: 5,
    height: 35,
    maxHeight: 30,
    alignSelf: 'center',
    // marginVertical: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 3,
  },
  participantNavText: {
    fontSize: Platform.OS === 'web' ? 20 : 18,
    color: '#fff',
    fontWeight: '400',
    alignSelf: 'center',
    textAlign: 'center',
    flex: 1,
  },
  roomNameContainer: {
    paddingHorizontal: 5,
    marginHorizontal: 5,
    height: 35,
    maxHeight: 30,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  roomNameText: {
    fontSize:18,
    color:'#fff',
  },
  recordingNav: {
    backgroundColor: '#FF6A6B',
    flex: .8,
    maxWidth: 150,
    paddingHorizontal: 2,
    height: 35,
    maxHeight: 30,
    alignSelf: 'center',
    // marginVertical: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 3,
    marginHorizontal: 5,
  },
  recordingNavText: {
    fontSize: Platform.OS === 'web' ? 19 : 17,
    color: '#fff',
    fontWeight: '400',
    alignSelf: 'center',
    textAlign: 'center',
    flex: .8,
    lineHeight: 35,
  },
  participantButton: {
    height: '80%',
    width: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    flex: 1,
  },
  layoutButton: {
    height: '90%',
    width: 40,
    marginLeft: 'auto',
    marginHorizontal: 20,
  },
  participantIcon: {
    flex: 1,
    margin: 1,
    resizeMode: 'contain',
  },
  recordingIcon: {
    flex: 0.3,
    margin: 1,
    resizeMode: 'contain',
  },
  videoView: {
    flex: 12,
    backgroundColor: '#333237',
    flexDirection: 'column',
  },
  videoViewInner: {
    flex: 8,
  },
  bottomBar: {
    flex: Platform.OS === 'web' ? 1.3 : 1.6,
    paddingHorizontal: Platform.OS === 'web' ? '20%' : '1%',
    backgroundColor: '#333237',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    position: 'relative',
    margin: 0,
    bottom: 0,
  },
  temp: {
    width: '100%',
    height: '100%',
    backgroundColor: '#333237',
  },
  gridRow: {
    flex: 1,
    flexDirection: 'row',
    width: '100%',
  },
  gridVideoContainer: {
    flex: 1,
    backgroundColor: '#333237',
    marginHorizontal: 'auto',
  },
  gridVideoContainerInner: {
    borderColor: '#eee',
    borderWidth:2,
    flex: 1,
    margin:2,
  },
  bottomBarButton: {
    height: '70%',
    width: 60,
    backgroundColor: '#6D767D',
  },
  participantView: {
    width: Platform.OS === 'web' ? '25%' : '50%',
    height: '100%',
    backgroundColor: '#6E757D',
    zIndex: 20,
    position: 'absolute',
  },
  participantContainer: {
    flexDirection: 'row',
    flex: 0.1,
    backgroundColor: '#6E757D',
    height: '15%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantText: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? 22 : 17,
    flexDirection: 'row',
    color: '#fff',
    lineHeight: 20,
    paddingLeft: 10,
    alignSelf: 'center',
  },
  participantCountTextHolder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  participantCountText: {
    fontSize: Platform.OS === 'web' ? 24 : 16,
    color: '#ABABAB',
    fontWeight: '500',
  },
  participantMicButton: {
    width: 17,
    height: 17,
    backgroundColor: '#777',
    marginTop: 10,
    marginLeft: 10,
  },
  participantButtonContainer: {
    flex: 0.3,
    flexDirection: 'row',
    paddingRight: 20,
    alignSelf: 'center',
  },
  pinnedView: {
    flex: 2,
    backgroundColor: '#333237',
    flexDirection: 'row',
  },
  pinnedVideo: {
    flex: 1,
    borderColor: '#eee',
    borderWidth:2
  },
  participantCountInner: {
    width: width / 7.5,
    height: width / 7.5,
    maxHeight: 100,
    maxWidth: 100,
    textAlignVertical: 'center',
    backgroundColor: '#444',
    borderRadius: width / 6,
    alignItems: 'center',
    marginHorizontal: 15,
    alignSelf: 'center',
  },
  localButton: {
    backgroundColor: '#6E757D',
    borderRadius: 2,
    borderColor: '#6E757D',
    width: 46,
    height: 46,
    display: 'flex',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  endCall: {
    backgroundColor: '#F86051',
    borderRadius: 2,
    borderColor: '#F86051',
    width: 46,
    height: 46,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  greenLocalButton: {
    backgroundColor: '#4BEB5B',
    borderRadius: 2,
    borderColor: '#F86051',
    width: 46,
    height: 46,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remoteViewTouchable: {
    width: width / 4,
    // borderRadius: 10,
    borderColor: '#fff',
    borderWidth: .8,
    marginHorizontal: 4,
    marginVertical: 10,
    zIndex: 40,
  },
  remoteViewTouchableWeb: {
    width: width / 8,
    marginRight: 10,
    marginVertical: 8,
    zIndex: 40,
  },
  remoteButton: {
    width: 25,
    height: 25,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    marginHorizontal: 0,
    backgroundColor: '#6E757D',
  },
  minCloseBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 25,
    height: 25,
    borderRadius: 0,
    position: 'absolute',
    right: 5,
    top: 5,
  },
  remoteBtnContainer: {
    bottom: 0,
    position: 'absolute',
    marginVertical: 0,
    marginBottom: 5,
  },
  callCompleteText: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? 26 : 22,
    flexDirection: 'row',
    color: '#fff',
    lineHeight: Platform.OS === 'web' ? 26 : 22,
    marginTop: '10%',
    alignSelf: 'center',
  },
  participantsButton: {
    height: '80%',
    width: 40,
    marginHorizontal: 20,
  },
  maxVideoContainer: {
    flex: 1,
    margin: 5,
  },
  participantsView: {
    width: Platform.OS === 'web' ? '25%' : '50%',
    height: '100%',
    backgroundColor: '#6E757D',
    zIndex: 20,
    position: 'absolute',
  },
  participantsText: {
    flex: 1,
    fontSize: Platform.OS === 'web' ? 22 : 17,
    flexDirection: 'row',
    color: '#fff',
    lineHeight: 20,
    paddingLeft: 10,
    alignItems: 'center',
    alignSelf: 'center',
  },
  participantsMicButton: {
    width: 17,
    height: 17,
    backgroundColor: '#777',
    marginTop: 10,
    marginLeft: 10,
  },
  participantsButtonContainer: {
    flex: 0.3,
    flexDirection: 'row',
    paddingRight: 20,
    alignSelf: 'center',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#009DEC',
  },
  mainContainerWeb: {
    flex: 1,
    backgroundColor: '#009DEC',
    //backgroundImage: 'linear-gradient(0deg, #0076D6, #02BFFC)',
    flexDirection: 'row',
  },
  imageContainer: {
    flex: 1,
    backgroundColor: '#ff0000',
  },
  contentContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: '10%',
    alignItems: 'center',
    paddingTop: '4%',
    marginTop: 80,
  },
  buttonText: {
    width: '100%',
    height: 40,
    lineHeight: 40,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: '#fff',
  },
  textBox: {
    width: '100%',
    textAlign: 'center',
    backgroundColor: '#007FD6',
    color: '#fff',
    marginBottom: 15,
    maxWidth: 500,
    minHeight: 40,
  },
  button: {
    width: '100%',
    backgroundColor: '#00C7FE',
    maxWidth: 500,
    minHeight: 40,
  },
  buttonDark: {
    width: '80%',
    backgroundColor: '#6E757D',
    maxWidth: 500,
    //minHeight: 60,
    alignSelf: 'center',
    marginBottom: '10%',
  },
  icons: {
    tintColor: '#fff',
    width: 175,
    height: 35,
    alignSelf: 'center',
    margin: 30,
    marginTop: 100,
  },
  logo: {
    tintColor: '#fff',
    width: 177,
    height: 45,
    alignSelf: 'center',
    marginBottom: 40,
  },
  hero: {
    width: '100%',
    height: '100%',
    aspectRatio: 1,
  },
  buttonIcon:{
    width: 25,
    height: 25,
    tintColor: '#fff',
  },
};

export default styles;
