import {Platform} from 'react-native';

const styles = {
  temp: {
    width: '100%',
    height: '100%',
    backgroundColor: $config.secondaryFontColor,
    borderRadius: 15,
  },
  bottomBar: {
    flex: Platform.OS === 'web' ? 1.3 : 1.6,
    paddingHorizontal: Platform.OS === 'web' ? '20%' : '1%',
    backgroundColor: $config.secondaryFontColor + 80,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    position: 'relative',
    margin: 0,
    bottom: 0,
  },
  localButton: {
    backgroundColor: $config.secondaryFontColor, //'#fff',
    borderRadius: 23,
    borderColor: $config.primaryColor,
    borderWidth: 0,
    width: 40,
    height: 40,
    display: 'flex',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  endCall: {
    backgroundColor: $config.secondaryFontColor, //'#fff',
    borderRadius: 23,
    borderColor: $config.primaryColor,
    borderWidth: 0,
    width: 40,
    height: 40,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  remoteButton: {
    width: 25,
    height: 25,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderWidth: 0,
    borderRightWidth: 0,
    borderLeftWidth: 0,
    marginHorizontal: 0,
    backgroundColor: $config.secondaryFontColor, //'#fff',
  },
  minCloseBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 25,
    height: 25,
    borderRadius: 0,
    position: 'absolute',
    right: 5,
    top: 5,
  },
};

export default styles;
